feat: added node name validation and fix data is not passed to restApi in Execution (#355)
* Added a health check RPC endpoint to avoid mixing with a regular ping endpoint for operators

* Update version.go to reply on go-semantic version and Github release

* Update Manual trigger to use node.data as output

* Added node name validation and fix data is not passed to restApi in Execution problem

* Solve manual trigger output data is not passed to subsequent node problem

* Extract common functions into  core/taskengine/node_utils.go

* Updated Manual Trigger adding headers and pathParams

* Update avs.proto for Manual Trigger

* Fix Rest API node input:undefined problem

* Fix filter and loop test failures

* Update core/taskengine/vm_runner_filter.go

Co-authored-by: Copilot <175728472+Copilot@users.noreply.github.com>

* Added more reserved keyword to avoid for node names

* Added vm_security to add code injection prevention to nodes

* Fixed FilterNode to use value.something to refer to iterable item

* Update Rest API node with more mocked response

* Update applyToFields of contractRead to specify methodName

* Address github copilot sanitization comments

* Added docs for the trigger and node input and data design

* Fix evenTrigger.data not available to subsequent node problem

* Simply manual trigger design to achieve cleaner code

* Fix step.input does not have runner in LoopNode issue

* Fix failing test of --- FAIL: TestBuildTriggerDataMapEventTriggerFlattening (0.00s)

* Fix loop node Step input undefined problem

* Added executionMode conversion

* Fix test cases and address copilot comments

* Fix sdk test failures

---------

Co-authored-by: Wei Lin <wei@avaprotocol.org>
Co-authored-by: Chris Li <chrisli30@users.noreply.github.com>
Co-authored-by: Copilot <175728472+Copilot@users.noreply.github.com>